/* Auto-generated by genmsg_cpp for file /home/n-31v/robotic-software/ros_workspace/nxt_lejos/nxt_lejos_msgs/msg/Battery.msg */
#ifndef NXT_LEJOS_MSGS_MESSAGE_BATTERY_H
#define NXT_LEJOS_MSGS_MESSAGE_BATTERY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace nxt_lejos_msgs
{
template <class ContainerAllocator>
struct Battery_ {
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
  : voltage(0.0)
  {
  }

  Battery_(const ContainerAllocator& _alloc)
  : voltage(0.0)
  {
  }

  typedef double _voltage_type;
  double voltage;


  typedef boost::shared_ptr< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nxt_lejos_msgs::Battery_<ContainerAllocator>  const> ConstPtr;
}; // struct Battery
typedef  ::nxt_lejos_msgs::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::nxt_lejos_msgs::Battery> BatteryPtr;
typedef boost::shared_ptr< ::nxt_lejos_msgs::Battery const> BatteryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nxt_lejos_msgs::Battery_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nxt_lejos_msgs::Battery_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nxt_lejos_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nxt_lejos_msgs::Battery_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cd1e97d74e6d797b46bc5a51e820e6ae";
  }

  static const char* value(const  ::nxt_lejos_msgs::Battery_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcd1e97d74e6d797bULL;
  static const uint64_t static_value2 = 0x46bc5a51e820e6aeULL;
};

template<class ContainerAllocator>
struct DataType< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nxt_lejos_msgs/Battery";
  }

  static const char* value(const  ::nxt_lejos_msgs::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 voltage\n\
\n\
";
  }

  static const char* value(const  ::nxt_lejos_msgs::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nxt_lejos_msgs::Battery_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nxt_lejos_msgs::Battery_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.voltage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Battery_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nxt_lejos_msgs::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nxt_lejos_msgs::Battery_<ContainerAllocator> & v) 
  {
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NXT_LEJOS_MSGS_MESSAGE_BATTERY_H

